name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        # uses: mathieudutour/github-tag-action@v6.2
        run: |
          if [[ "$(git tag -l v* | wc -l)" -eq 0 ]]; then
            VERSION='0'
          else
            VERSION=$(git describe --tags --abbrev=0 | sed -e 's/v//')
            ((VERSION++))
          fi

          git tag -a "v$VERSION" -m "v$VERSION"
          git push --tags
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/flexxyfluxx/kibty.net
          tags: |
            type=raw,value=latest
            type=sha
            type=raw,value=${{ steps.tag_version.outputs.new_tag }}

          labels: |
            org.opencontainers.image.source=https://github.com/flexxyfluxx/kibty.net

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
